"""added title to book model

Revision ID: 21df1d496183
Revises: 380c26d0df36
Create Date: 2024-12-08 14:30:09.028936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21df1d496183'
down_revision = '380c26d0df36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
