"""Add Test table

Revision ID: 8289739d45ec
Revises: 
Create Date: 2024-12-05 19:31:35.269151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8289739d45ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Test1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_data', sa.String(), nullable=True),
    sa.Column('test_data2', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Test1')
    # ### end Alembic commands ###
