"""add tag table

Revision ID: fa303ea82763
Revises: 50951dcb29af
Create Date: 2024-12-07 22:21:36.353253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa303ea82763'
down_revision = '50951dcb29af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('best_seller', sa.Boolean(), nullable=False),
    sa.Column('fiction', sa.Boolean(), nullable=False),
    sa.Column('award_winner', sa.Boolean(), nullable=False),
    sa.Column('new_release', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    # ### end Alembic commands ###
